### ISSUE TITLE
npm run generate-vendor-bundle error 

### ISSUE THREAD

**Issue by taven-liu** [secoya/typescript-relay-modern#1]
D:\data\code\relay\typescript-relay-modern\node_modules\.bin\webpack:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at Object.<anonymous> (D:\data\code\relay\typescript-relay-modern\node_modules\ts-node\src\_bin.ts:182:12)
    at Module._compile (module.js:570:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! typescript-relay-modern@1.0.0 generate-vendor-bundle: `ts-node -P ./config/tsconfig.json ./node_modules/.bin/webpack --config ./config/vendor-bundles.webpack.config.ts -p`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the typescript-relay-modern@1.0.0 generate-vendor-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

node 6.10.2
npm 5.3.0

**Comment by taven-liu** [comment]
it can't work in Window 10

**Comment by thetrompf** [comment]
Hi Taven

Which shell are you using: cmd, powershell or mingw/gitbash?

It appears that your shell is trying to run the macOS/linux version of the webpack bin, instead of the windows version: `.\node_modules\.bin\webpack.cmd`.

**Comment by taven-liu** [comment]
powershell, how to instead of  `webpack.cmd`  thanks
